name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publishing to Thunderstore
        id: publish
        uses: ./
        with:
          token: ${{ secrets.TS_KEY }}
          namespace: dhkatz
          name: ThunderstorePublish
          description: From the thunderstore-publish GitHub Action
          version: v0.${{ github.run_number }}.${{ github.run_attempt }}
          communities: riskofrain2
          repo: thunderstore.dev
          categories: |
            mods
            maps
            tools
            items
          deps: |
            GreenTF-test@2708437257.35.1
          dev: true

      - name: Output Thunderstore URL
        run: echo ${{ steps.publish.outputs.url }}
