name: Test Action

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: pub
        uses: ./
        with:
          namespace: dhkatz
          name: ThunderstorePublish
          dev: true
          token: ${{ secrets.TS_KEY }}
          description: From the thunderstore-publish GitHub Action
          version: v0.${{ github.run_number }}.0
          communities: riskofrain2
          repo: thunderstore.dev
          categories: |
            mods
            maps
            tools
            items
          deps: |
            GreenTF-test@2708437257.35.1
      - run: echo ${{ steps.pub.outputs.url }}
